server:
  port: 8011
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andypengqingsong/spring-cloud-config-repo.git
          search-paths: spring-cloud-config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
       #  设置服务名
